/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        Pessoa leozinho = new Pessoa("Leozinho","171");
        Pessoa professorMello = new Pessoa("Emerson", "190");

        leozinho.setCpf("666.666.666-48");
        professorMello.setCpf("123.456.789-00");
        leozinho.setNome("Leozinho");
        professorMello.setNome("Emerson");
        System.out.println("Nome: " + leozinho.getNome());
        System.out.println(leozinho.getCpf());
        System.out.println("Nome: " + professorMello.getNome());
        System.out.println(professorMello.getCpf());
        Estudante leo = new Estudante(5,900, 19);
        
        System.out.println(leo);

        Estudante zero = new Estudante(0, 0, 0);

        System.out.println(zero.getTotal());
    }
}
