/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {


    public static void main(String[] args) {

        List<Carta> baralho = new ArrayList<>();

        for(Naipe naipe : Naipe.values()){
            for(ValorCarta valor : ValorCarta.values()){
                baralho.add(new Carta(valor, naipe));
            }
        }
//        for(Carta c: baralho){ //imprimir toda a arraylist
//            System.out.println(c);
//        }
        Collections.shuffle(baralho); //imrpimir o baralho aleatorio
        for(Carta c: baralho){
            System.out.println(c);
        }
//        DiaDaSemana[] aulas = {DiaDaSemana.TER, DiaDaSemana.QUI};
//
//        int disco = aulas[0].code;//pode ser um input do usuario
//
//        DiaDaSemana relatorio = DiaDaSemana.getByCode(disco);
//
//        if (relatorio != null) { //se relatorio for diferente (ou seja, retornar algo, vai printar ele
//            System.out.println(relatorio);
//
//        }
//
    }
}
